<?php

namespace fengdangxing\db;

use yii\elasticsearch\ActiveRecord;

class YiiElasticsearchSql extends ActiveRecord
{
    use TraitType;
    use TraitSelect;
    use TraitSelectAgg;

    public function init()
    {
        \Yii::$app->response->send();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 这个就是第二步配置的组件的名字（key值）
     * @author 1
     * @version v2.1
     * @date: 2020/10/18
     * @return null|object|\yii\elasticsearch\Connection
     * @throws \yii\base\InvalidConfigException
     */
    public static function getDb()
    {
        return \Yii::$app->get('elasticsearch');
    }

    /**
     * @desc 文档类型-7取消该类型
     * @author 1
     * @version v2.1
     * @date: 2020/10/18
     * @return string
     */
    public static function type()
    {
        return '_doc';
    }

    /**
     * @return array This model's mapping
     */
    public static function mapping()
    {
        return [
            'properties' => [
                'first_name' => ['type' => 'text'],
                'last_name' => ['type' => 'text'],
                'order_ids' => ['type' => 'keyword'],
                'email' => ['type' => 'keyword'],
                'registered_at' => ['type' => 'date'],
                'updated_at' => ['type' => 'date'],
                'status' => ['type' => 'keyword'],
                'is_active' => ['type' => 'boolean'],
            ]
        ];
    }

    /**
     * @desc 更新索引结构
     * @author 1
     * @version v2.1
     * @date: 2020/10/19
     * @throws \yii\base\InvalidConfigException
     */
    public static function updateMapping()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->setMapping(static::index(), static::type(), static::mapping());
    }

    /**
     * @desc 创建索引
     * @author 1
     * @version v2.1
     * @date: 2020/10/19
     * @throws \yii\base\InvalidConfigException
     */
    public static function createIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->createIndex(static::index(), [
            //'aliases' => [ /* ... */ ],
            'mappings' => static::mapping(),
            //'settings' => [ /* ... */ ],
        ]);
    }

    /**
     * @desc 删除索引
     * @author 1
     * @version v2.1
     * @date: 2020/10/19
     * @throws \yii\base\InvalidConfigException
     */
    public static function deleteIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->deleteIndex(static::index(), static::type());
    }

    /**
     * @desc 增加数据
     * @author 1
     * @version v2.1
     * @date: 2020/10/20
     * @param array $data
     * @param string $id
     * @throws \yii\base\InvalidConfigException
     */
    public static function addData($data = array(), $id = null)
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->insert(static::index(), static::type(), $data, $id);
    }
}
